BitcoinKit.xcodeproj/project.pbxproj
BitcoinKit/Opcode.swift
BitcoinKit/Script.swift
BitcoinKit/ScriptChunk.swift
BitcoinKit/ScriptChunkHelper.swift

- Refactor `Script.swift`, `ScriptChunk.swift`
- Add `ScriptChunkHelper.swift`

Refactor script

---

.github/ISSUE_TEMPLATE/---bug-report.md
.github/ISSUE_TEMPLATE/---feature-request.md

Added issue templates for bug report and feature request.
close #22

:pencil2: update issue templates

---

BitcoinKit/TransactionOutPoint.swift

close #24 
Modify deserialization of TransactionOutPoint

:fire: modify deserialization

---

BitcoinKit/Address.swift
BitcoinKit/Script.swift

- Address initializer with data
- Refactor AddressError
closes #4

:sparkles: Add Address initializer with data

---

BitcoinCashKit/OpCodeFactory.swift

close #163 
Added a doc to OpCodeFactory.

Add documentation to OpCodeFactory

---

BitcoinCashKit/OpCodeFactory.swift
BitcoinCashKit/PrivateKey.swift
BitcoinCashKit/Script.swift
BitcoinCashKit/ScriptChunk.swift
BitcoinCashKit/ScriptExecutionContext.swift
BitcoinCashKit/ScriptMachine.swift
BitcoinCashKitTests/ScriptMachineTests.swift

- ScriptMachine : class -> struct
- Some internal func -> public

♻️ Refactor script machine

---

BitcoinCashKit.xcodeproj/project.pbxproj
BitcoinCashKit/Address.swift
BitcoinCashKit/Encoding.swift
BitcoinCashKit/OP_EXAMPLE.swift
BitcoinCashKit/OpCodeProtocol.swift
BitcoinCashKit/Opcode.swift
BitcoinCashKit/Peer.swift
BitcoinCashKit/PeerGroup.swift
BitcoinCashKit/Script.swift
BitcoinCashKit/ScriptChunkHelper.swift
BitcoinCashKit/Transaction+SignatureHash.swift
BitcoinCashKit/TransactionSignatureSerializer.swift
Examples/Wallet/Wallet/HomeViewController.swift
Examples/Wallet/Wallet/SendViewController.swift

Remove unnecessary TODOs and create issues instead

✌️ Resolve TODOs

---

BitcoinCashKit.xcodeproj/project.pbxproj
BitcoinCashKit/OP_1NEGATE.swift
BitcoinCashKit/ScriptExecutionContext.swift

Add opcode OP_1NEGATE

---

README.md

I designed the icon for BitcoinCashKit

Add image into README.md

---

BitcoinCashKit.xcodeproj/project.pbxproj
BitcoinCashKit/OP_CHECKMULTISIG.swift
BitcoinCashKit/OP_CHECKMULTISIGVERIFY.swift
BitcoinCashKit/OP_CHECKSIG.swift
BitcoinCashKit/OP_CHECKSIGVERIFY.swift
BitcoinCashKit/OP_DUP.swift
BitcoinCashKit/OP_EQUAL.swift
BitcoinCashKit/OP_EQUALVERIFY.swift
BitcoinCashKit/OP_HASH160.swift
BitcoinCashKit/OP_VERIFY.swift
BitcoinCashKit/OpCodeProtocol.swift
BitcoinCashKit/Opcode.swift
BitcoinCashKit/ScriptExecutionContext.swift

Add OP_CHECKMULTISIG

---

BitcoinCashKit.xcodeproj/project.pbxproj
BitcoinCashKit/OP_SWAP.swift

:pencil2: add OP_SWAP

---

BitcoinCashKit.xcodeproj/project.pbxproj
BitcoinCashKit/OP_SWAP.swift
BitcoinCashKit/ScriptExecutionContext.swift
BitcoinCashKitTests/OpCodeTests.swift

`OpCodeTests`
- Implement OP_CODE tests.
`ScriptExecutionContext`
- Fix resetStack()
- OP_VERIFY
- OP_DUP

Add tests/opcode tests

---

BitcoinCashKit/Script.swift
BitcoinCashKitTests/ScriptTests.swift

add test to create 2of3 multisig script

Add test to create multisig address

---

BitcoinCashKit.xcodeproj/project.pbxproj
BitcoinCashKit/Core/Scripts/OP_CODE/OP_MAX.swift
BitcoinCashKit/Core/Scripts/Opcode.swift

:pencil2: add OP_MAX

---

BitcoinCashKit.xcodeproj/project.pbxproj
BitcoinCashKit/Core/Scripts/OP_CODE/OP_MIN.swift
BitcoinCashKit/Core/Scripts/Opcode.swift

:pencil2: add OP_MIN

---

BitcoinCashKit.xcodeproj/project.pbxproj
BitcoinCashKit/Core/Scripts/OP_CODE/OP_1SUB.swift
BitcoinCashKit/Core/Scripts/Opcode.swift

:pencil2: add OP_1SUB

---

BitcoinCashKit.xcodeproj/project.pbxproj
BitcoinCashKit/Core/Scripts/OP_CODE/OP_NEGATE.swift
BitcoinCashKit/Core/Scripts/Opcode.swift

:pencil2: add OP_NEGATE

---

BitcoinCashKit.xcodeproj/project.pbxproj
BitcoinCashKit/Core/Scripts/OP_CODE/OP_2DIV.swift
BitcoinCashKit/Core/Scripts/Opcode.swift

:pencil2: add OP_2DIV

---

BitcoinCashKit.xcodeproj/project.pbxproj
BitcoinCashKit/Core/Scripts/OP_CODE/OP_2MUL.swift
BitcoinCashKit/Core/Scripts/Opcode.swift

:pencil2: add OP_2MUL

---

BitcoinCashKit.xcodeproj/project.pbxproj
BitcoinCashKit/Core/Scripts/OP_CODE/OP_NOT.swift
BitcoinCashKit/Core/Scripts/Opcode.swift

:pencil2: add OP_NOT

---

BitcoinCashKit.xcodeproj/project.pbxproj
BitcoinCashKit/Core/Scripts/OP_CODE/OP_0NOTEQUAL.swift
BitcoinCashKit/Core/Scripts/Opcode.swift

:pencil2: add OP_0NOTEQUAL

---

BitcoinCashKit.xcodeproj/project.pbxproj
BitcoinCashKit/Core/Scripts/OP_CODE/OP_1ADD.swift
BitcoinCashKit/Core/Scripts/Opcode.swift

:pencil2: add OP_1ADD

---

BitcoinCashKit.xcodeproj/project.pbxproj
BitcoinCashKit/Core/Scripts/OP_CODE/OP_ADD.swift
BitcoinCashKit/Core/Scripts/Opcode.swift

:pencil2: add OP_ADD

---

BitcoinCashKit.xcodeproj/project.pbxproj
BitcoinCashKit/Core/Scripts/OP_CODE/OP_RSHIFT.swift
BitcoinCashKit/Core/Scripts/Opcode.swift

:pencil2: add OP_RSHIFT

---

BitcoinCashKit/Core/Scripts/OP_CODE/OP_CHECKSIG.swift
BitcoinCashKit/Core/Scripts/OpCodeProtocol.swift
BitcoinCashKit/Core/Scripts/ScriptExecutionContext.swift
BitcoinCashKitTests/OpCodeTests.swift

Added verbose property for ScriptExecutionContext

Context verbose property

---

BitcoinCashKit/Core/HDPrivateKey.swift
BitcoinCashKit/Core/HDPublicKey.swift
BitcoinCashKit/Wallet/HDWallet.swift
Examples/Wallet/Wallet/SendViewController.swift

♻️ Refactor HDKeys and HDWallet

---

BitcoinCashKitTests/OpCodeTests.swift

close https://github.com/BitcoinCashKit/BitcoinCashKit/issues/274
I added tests for `OP_1NEGATE`
And, implemented helper method.

Add tests for OP_1NEGATE

---

BitcoinCashKitTests/OpCodeTests.swift

close https://github.com/BitcoinCashKit/BitcoinCashKit/issues/278
I added tests for OP_EQUAL.
Please review.

Add tests for OP_EQUAL

---

BitcoinCashKit.xcodeproj/project.pbxproj
BitcoinCashKit/Core/Scripts/OP_CODE/OP_RETURN.swift
BitcoinCashKit/Core/Scripts/Opcode.swift

✨ Add OP_RETURN

---

BitcoinCashKitTests/OpCodeTests.swift

close https://github.com/BitcoinCashKit/BitcoinCashKit/issues/282

Add tests for OP_HASH160

---

BitcoinCashKit.xcodeproj/project.pbxproj
BitcoinCashKit/Core/Scripts/OP_CODE/Control Flow Operators/OP_ELSE.swift
BitcoinCashKit/Core/Scripts/OP_CODE/Control Flow Operators/OP_ENDIF.swift
BitcoinCashKit/Core/Scripts/OP_CODE/Control Flow Operators/OP_IF.swift
BitcoinCashKit/Core/Scripts/OP_CODE/Control Flow Operators/OP_NOP.swift
BitcoinCashKit/Core/Scripts/OP_CODE/Control Flow Operators/OP_NOTIF.swift
BitcoinCashKit/Core/Scripts/OP_CODE/Control Flow Operators/OP_RETURN.swift
BitcoinCashKit/Core/Scripts/OP_CODE/Control Flow Operators/OP_VER.swift
BitcoinCashKit/Core/Scripts/OP_CODE/Control Flow Operators/OP_VERIF.swift
BitcoinCashKit/Core/Scripts/OP_CODE/Control Flow Operators/OP_VERNOTIF.swift
BitcoinCashKit/Core/Scripts/OpCodeProtocol.swift

closes #34 
closes #35 
closes #36 
closes #37 
closes #39 
closes #38 
closes #40 
closes #41 
Add
- OP_NOP
- OP_VER
- OP_IF
- OP_NOTIF
- OP_VERIF
- OP_VERNOTIF
- OP_ELSE
- OP_ENDIF

✨ Add control flow operators

---

BitcoinCashKitTests/OpCodeTests.swift

close https://github.com/BitcoinCashKit/BitcoinCashKit/issues/283

Add test for OP_INVALIDOPCODE

---

BitcoinCashKit/Core/Scripts/OP_CODE/Pseudo Words/OP_INVALIDOPCODE.swift
BitcoinCashKit/Core/Scripts/OP_CODE/Push Data/OP_0.swift
BitcoinCashKit/Core/Scripts/OpCodeProtocol.swift
BitcoinCashKitTests/OpCodeTests.swift

Modify preprocess with reference to
https://github.com/Bitcoin-ABC/bitcoin-abc/blob/master/src/script/interpreter.cpp#L360

Modify opcode preprocess

---

BitcoinCashKit.xcodeproj/project.pbxproj
BitcoinCashKit/Core/Scripts/OP_CODE/Pseudo Words/OP_PUBKEY.swift
BitcoinCashKit/Core/Scripts/OP_CODE/Pseudo Words/OP_PUBKEYHASH.swift
BitcoinCashKit/Core/Scripts/Opcode.swift

✨ Add OP_PUBKEYHASH, OP_PUBKEY

Add pseudo words

---

BitcoinCashKit/Core/Scripts/OP_CODE/Lock Time/OP_CHECKLOCKTIMEVERIFY.swift
BitcoinCashKit/Core/Scripts/OP_CODE/Lock Time/OP_CHECKSEQUENCEVERIFY.swift
BitcoinCashKit/Core/Scripts/OP_CODE/Pseudo Words/OP_PUBKEY.swift
BitcoinCashKit/Core/Scripts/OP_CODE/Pseudo Words/OP_PUBKEYHASH.swift
BitcoinCashKit/Core/Scripts/ScriptExecutionContext.swift
BitcoinCashKit/Core/Scripts/ScriptMachine.swift
BitcoinCashKit/Core/UnitsAndLimits.swift

closes #334 
closes #333 
Add 
- OP_CHECKLOCKTIMEVERIFY
- OP_CHECKSEQUENCEVERIFY
https://github.com/bitcoin/bips/blob/master/bip-0065.mediawiki
https://github.com/bitcoin/bips/blob/master/bip-0112.mediawiki
https://en.bitcoin.it/wiki/Script
https://github.com/Bitcoin-ABC/bitcoin-abc/blob/73c5e7532e19b8f35fcf73255cd1d0df67607cd2/src/script/interpreter.cpp#L420

:sparkles: Add OP_CHECKLOCKTIMEVERIFY, OP_CHECKSEQUENCEVERIFY

---

Examples/WalletWithAPI/WalletWithAPI.xcodeproj/project.pbxproj
Examples/WalletWithAPI/WalletWithAPI/APIClient.swift
Examples/WalletWithAPI/WalletWithAPI/AppController.swift
Examples/WalletWithAPI/WalletWithAPI/AppDelegate.swift
Examples/WalletWithAPI/WalletWithAPI/Assets.xcassets/AppIcon.appiconset/Contents.json
Examples/WalletWithAPI/WalletWithAPI/Assets.xcassets/Contents.json
Examples/WalletWithAPI/WalletWithAPI/HomeViewController.swift
Examples/WalletWithAPI/WalletWithAPI/Info.plist
Examples/WalletWithAPI/WalletWithAPI/LaunchScreen.storyboard
Examples/WalletWithAPI/WalletWithAPI/Main.storyboard
Examples/WalletWithAPI/WalletWithAPI/SendViewController.swift
Examples/WalletWithAPI/WalletWithAPI/Transaction.swift
Examples/WalletWithAPI/WalletWithAPI/UnspentOutput.swift

Added another sample wallet using API

:star: add another sample wallet using API

---

BitcoinCashKit/Core/Scripts/OP_CODE/Crypto/OP_CHECKMULTISIG.swift

Fixed name of `OP_CHECKMULTISIG `

:recycle: fix name

---

BitcoinCashKit.xcodeproj/project.pbxproj
BitcoinCashKit/Core/PrivateKey.swift
BitcoinCashKit/Core/Scripts/OP_CODE/Bitwise Logic/OP_EQUALVERIFY.swift
BitcoinCashKit/Core/Scripts/OpCodeProtocol.swift
BitcoinCashKit/Core/Scripts/Script.swift
BitcoinCashKit/Core/Scripts/ScriptExecutionContext.swift
BitcoinCashKit/Core/Serialization.swift
BitcoinCashKit/Mock/MockHelper.swift
BitcoinCashKit/Mock/MockKey.swift
BitcoinCashKit/MockHelper.swift
BitcoinCashKitTests/MockHelperTests.swift
BitcoinCashKitTests/OpCodeTests.swift

Add script mock helper

---

BitcoinCashKit/Core/Scripts/Script.swift
BitcoinCashKit/Core/TransactionSignatureSerializer.swift
BitcoinCashKitTests/MockHelperTests.swift
BitcoinCashKitTests/ScriptMachineTests.swift

- `Script.append()`
- `Script.appendData()`
- `Script.appendScript()`
- `Script. deleteOccurrences()` 
became method chain function!

♻️ Modify Script.append() as method chain function

---

BitcoinCashKit/Core/Scripts/Script.swift
BitcoinCashKit/Core/Scripts/ScriptChunk.swift
BitcoinCashKit/Core/Scripts/ScriptExecutionContext.swift
BitcoinCashKit/Core/Scripts/ScriptMachine.swift
BitcoinCashKit/Mock/MockKey.swift
BitcoinCashKitTests/MockHelperTests.swift

- Fix some issues related to P2SH
- Add test cases of raw/P2SH multi-sig script mock

Add script hash mock test
